const DOCS_CONTENT = {
  en: {
    common: {
      docsBadge: "Docs",
      documentation: "Documentation",
      gitLumaDocs: "GitLuma Docs",
      home: "Home",
      backToHome: "Back to Home",
      backToDocs: "Back to Docs",
      allDocs: "All Docs",
      onThisPage: "On this page",
      navigate: "Navigate",
      searchDocs: "Search docs...",
      statusLive: "v2.0 - Live",
      lastUpdated: "Last updated: April 2026",
      copy: "Copy",
      copied: "Copied!",
      closeDocsNavigation: "Close documentation navigation",
      closeNavigation: "Close navigation",
      themeLight: "Light mode",
      themeDark: "Dark mode",
      linkedTopic: "Documentation topic linked from the landing page",
    },
    nav: [
      {
        id: "getting-started",
        label: "Getting Started",
        path: "/docs/getting-started",
        sections: [
          { id: "installation", label: "Installation" },
          { id: "quick-start-in-3-steps", label: "Quick Start in 3 Steps" },
          { id: "system-requirements", label: "System Requirements" },
          { id: "troubleshooting", label: "Troubleshooting" },
        ],
      },
      {
        id: "api-reference",
        label: "API Reference",
        path: "/docs/api-reference",
        sections: [
          { id: "base-url", label: "Base URL" },
          { id: "authentication", label: "Authentication" },
          { id: "projects", label: "Projects" },
          { id: "commits", label: "Commits" },
          { id: "invites", label: "Invites" },
          { id: "webhooks", label: "Webhooks" },
          { id: "error-codes", label: "Error Codes" },
        ],
      },
      {
        id: "cli",
        label: "CLI Tool",
        path: "/docs/cli-tool",
        sections: [
          { id: "installation", label: "Installation" },
          { id: "core-commands", label: "Core Commands" },
          { id: "project-management", label: "Project Management" },
          { id: "configuration", label: "Configuration" },
          { id: "flags-options", label: "Flags & Options" },
        ],
      },
      {
        id: "integrations",
        label: "Integrations",
        path: "/docs/integrations",
        sections: [
          { id: "github-oauth", label: "GitHub OAuth" },
          { id: "webhook-setup", label: "Webhook Setup" },
          { id: "socket-events", label: "Socket Events" },
          { id: "cicd-integration", label: "CI/CD Integration" },
        ],
      },
      {
        id: "auth",
        label: "Authentication",
        path: "/docs/authentication",
        sections: [
          { id: "overview", label: "Overview" },
          { id: "jwt-tokens", label: "JWT Tokens" },
          { id: "oauth-flow", label: "OAuth Flow" },
          { id: "api-keys", label: "API Keys" },
          { id: "refresh-tokens", label: "Refresh Tokens" },
        ],
      },
      {
        id: "sdk",
        label: "SDK",
        path: "/docs/sdk",
        sections: [
          { id: "installation", label: "Installation" },
          { id: "quick-start", label: "Quick Start" },
          { id: "projects-api", label: "Projects API" },
          { id: "commits-api", label: "Commits API" },
          { id: "typescript-types", label: "TypeScript Types" },
        ],
      },
    ],
    hub: {
      title: "GitLuma Documentation",
      description: "Everything you need to connect GitHub, automate workflows and track your team's commits in real time.",
      primaryCta: "Get Started",
      secondaryCta: "API Reference",
      stats: [
        { end: 99, suffix: "%", label: "Uptime SLA" },
        { end: 500, suffix: "ms", label: "Avg response" },
        { end: 12, suffix: "k+", label: "API calls/min" },
      ],
      quickStartTitle: "Quick Start",
      quickCards: [
        { id: "install-cli", title: "Install CLI", desc: "Set up GitLuma CLI in under 60 seconds.", href: "/docs/cli-tool", color: "#E8654A" },
        { id: "connect-github", title: "Connect GitHub", desc: "One-click OAuth and webhook setup.", href: "/docs/getting-started", color: "#3A7EE8" },
        { id: "api-keys", title: "API Keys", desc: "Generate and manage personal access tokens.", href: "/docs/authentication", color: "#22B07D" },
        { id: "sdk-reference", title: "SDK Reference", desc: "JavaScript and TypeScript SDK with full types.", href: "/docs/sdk", color: "#9B59B6" },
        { id: "guides", title: "Guides", desc: "Step-by-step guides for common workflows.", href: "/docs/getting-started", color: "#F39C12" },
        { id: "rest-api", title: "REST API", desc: "Full REST API with OpenAPI 3.0 schema.", href: "/docs/api-reference", color: "#E84A7A" },
      ],
      featureGuidesTitle: "Feature Guides",
      featureGuides: [
        {
          id: "real-time-notifications",
          title: "Real-time Notifications",
          summary: "GitLuma pushes commit, branch and activity events to the UI instantly over WebSockets, so your team sees new work without refreshing the page.",
          bullets: [
            "Push events are streamed to every connected project member in real time.",
            "Presence and activity cards stay in sync without polling loops.",
            "You can subscribe per project to keep event traffic scoped and fast.",
          ],
          language: "javascript",
          code: `const socket = io("wss://api.gitluma.io");\n\nsocket.emit("project:subscribe", {\n  projectId: "my-awesome-app",\n});\n\nsocket.on("commit:created", (event) => {\n  console.log(event.message, event.author, event.timestamp);\n});`,
        },
        {
          id: "github-integration",
          title: "GitHub Integration",
          summary: "Connect your repository once and GitLuma handles webhook creation, repo access and commit ingestion automatically.",
          bullets: [
            "OAuth connection links the selected GitHub account securely.",
            "Webhook setup is created during project initialization.",
            "Branches, PR references and commit metadata are synced into the dashboard.",
          ],
          language: "bash",
          code: `gitluma auth login\n# Authorize GitHub access in the browser\n\ngitluma init\n# Repository linked and webhook configured automatically`,
        },
        {
          id: "team-collaboration",
          title: "Team Collaboration",
          summary: "Projects support shared workspaces with live member presence, role-based access and task visibility so everyone knows who is doing what.",
          bullets: [
            "Owners can invite members and control project access.",
            "Member activity, current tasks and recent work stay visible in one place.",
            "Shared boards make it easier to coordinate design, code and review work.",
          ],
          language: "json",
          code: `{\n  "project": "my-awesome-app",\n  "members": [\n    { "name": "Ali", "role": "owner", "status": "online" },\n    { "name": "Maya", "role": "member", "status": "reviewing" }\n  ],\n  "liveBoard": true\n}`,
        },
        {
          id: "email-invitations",
          title: "Email Invitations",
          summary: "Invite teammates by email with shareable join links, automatic project assignment and the ability to resend or revoke invitations whenever needed.",
          bullets: [
            "Each invitation is tied to a project and intended role.",
            "Accepted invites add the user directly into the workspace.",
            "Pending invites can be re-sent, revoked or audited from one list.",
          ],
          language: "javascript",
          code: `await fetch("https://api.gitluma.io/api/invites", {\n  method: "POST",\n  headers: {\n    Authorization: "Bearer YOUR_TOKEN",\n    "Content-Type": "application/json",\n  },\n  body: JSON.stringify({\n    email: "alex@team.dev",\n    projectId: "my-awesome-app",\n    role: "member",\n  }),\n});`,
        },
      ],
      installation: {
        title: "Installation",
        intro: "Install the GitLuma CLI globally via npm or yarn:",
        authTitle: "Authenticate with GitHub",
        projectTitle: "Initialize a project",
      },
      apiReference: {
        title: "API Reference",
        endpoints: [
          { method: "GET", path: "/api/projects", desc: "List all projects for authenticated user", color: "#22B07D" },
          { method: "POST", path: "/api/projects", desc: "Create a new project linked to a repository", color: "#3A7EE8" },
          { method: "GET", path: "/api/projects/:id", desc: "Get project details by ID", color: "#22B07D" },
          { method: "DELETE", path: "/api/projects/:id", desc: "Delete a project and unlink webhook", color: "#E84A7A" },
          { method: "GET", path: "/api/commits/:projId", desc: "Paginated commit history for a project", color: "#22B07D" },
          { method: "POST", path: "/api/invites", desc: "Send email invite to join a project", color: "#3A7EE8" },
        ],
        exampleTitle: "Example request",
      },
      webhooks: {
        title: "Webhooks",
        intro: "GitLuma auto-registers a webhook on your GitHub repo. You can also register manually:",
      },
    },
    pages: {
      gettingStarted: {
        title: "Getting Started",
        description: "Get up and running with GitLuma in minutes. Learn the basics and set up your first project.",
        sections: [
          { id: "installation", label: "Installation" },
          { id: "quick-start-in-3-steps", label: "Quick Start in 3 Steps" },
          { id: "system-requirements", label: "System Requirements" },
          { id: "troubleshooting", label: "Troubleshooting" },
        ],
        installationTitle: "Installation",
        installationIntro: "Install the GitLuma CLI globally via npm or yarn:",
        quickStartTitle: "Quick Start in 3 Steps",
        quickStartSteps: [
          { title: "Step 1: Authenticate", desc: "Connect your GitHub account securely with OAuth" },
          { title: "Step 2: Initialize Project", desc: "Link your repository to GitLuma" },
          { title: "Step 3: Start Tracking", desc: "View commits and team activity in real time" },
        ],
        authenticateTitle: "Authenticate with GitHub",
        systemRequirementsTitle: "System Requirements",
        minimumTitle: "Minimum",
        minimumItems: ["Node.js 14.0+", "npm 6.0+ or yarn 1.22+", "Git 2.0+"],
        recommendedTitle: "Recommended",
        recommendedItems: ["Node.js 18.0+", "Latest npm or yarn", "GitHub Enterprise support"],
        troubleshootingTitle: "Troubleshooting",
        commandNotFoundTitle: "Command not found",
        authFailedTitle: "Authentication failed",
        authFailedIntro: "Clear your auth cache and try again:",
      },
      apiReference: {
        title: "API Reference",
        description: "Complete API documentation for integrating GitLuma into your applications.",
        sections: [
          { id: "base-url", label: "Base URL" },
          { id: "authentication", label: "Authentication" },
          { id: "projects", label: "Projects" },
          { id: "commits", label: "Commits" },
          { id: "invites", label: "Invites" },
          { id: "webhooks", label: "Webhooks" },
          { id: "error-codes", label: "Error Codes" },
        ],
        exampleRequest: "Example Request:",
        response: "Response:",
        baseUrlTitle: "Base URL",
        baseUrlIntro: "All REST requests should be sent to the GitLuma API base URL.",
        authenticationTitle: "Authentication",
        authenticationIntro: "All API requests require authentication using Bearer tokens:",
        endpointsTitle: "Endpoints",
        projectsTitle: "Projects",
        commitsTitle: "Commits",
        invitesTitle: "Invites",
        webhooksTitle: "Webhooks",
        webhooksIntro: "Use GitHub webhooks to push commit activity into GitLuma in real time.",
        errorCodesTitle: "Error Codes",
        errorCodesIntro: "API errors return standard HTTP status codes:",
        rateLimitingTitle: "Rate Limiting",
        freeTierTitle: "Free Tier",
        freeTierDesc: "1,000 requests per minute",
        proTierTitle: "Pro Tier",
        proTierDesc: "10,000 requests per minute",
        endpoints: {
          projects: [
            { method: "GET", path: "/api/projects", desc: "List all projects for authenticated user", color: "#22B07D" },
            { method: "POST", path: "/api/projects", desc: "Create a new project linked to a repository", color: "#3A7EE8" },
            { method: "GET", path: "/api/projects/:id", desc: "Get project details by ID", color: "#22B07D" },
          ],
          commits: [
            { method: "GET", path: "/api/commits/:projId", desc: "Paginated commit history for a project", color: "#22B07D" },
          ],
          invites: [
            { method: "POST", path: "/api/invites", desc: "Send email invite to join a project", color: "#3A7EE8" },
          ],
        },
      },
      cliTool: {
        title: "CLI Tool",
        description: "Master the GitLuma command-line interface to manage projects and track commits.",
        sections: [
          { id: "installation", label: "Installation" },
          { id: "core-commands", label: "Core Commands" },
          { id: "project-management", label: "Project Management" },
          { id: "configuration", label: "Configuration" },
          { id: "flags-options", label: "Flags & Options" },
        ],
        output: "Output:",
        installationTitle: "Installation",
        coreCommandsTitle: "Core Commands",
        authenticationTitle: "Authentication",
        projectManagementTitle: "Project Management",
        teamManagementTitle: "Team Management",
        commitsTrackingTitle: "Commits & Tracking",
        configurationTitle: "Configuration",
        configFileTitle: "Config File",
        configFileIntro: "Your CLI configuration is stored in:",
        flagsTitle: "Flags & Options",
        tipsTitle: "Tips & Tricks",
        useAliasesTitle: "Use Aliases",
        automatedSetupTitle: "Automated Setup",
        commands: {
          authLogin: "Authenticate with your GitHub account",
          authLogout: "Log out and remove stored credentials",
          authStatus: "Check current authentication status",
          init: "Initialize a GitLuma project in current repo",
          projectsList: "List all your projects",
          projectsInfo: "Get detailed info about a project",
          invite: "Invite a team member to your project",
          membersList: "List project members",
          commitsList: "View recent commits in project",
          commitsStats: "Get commit statistics",
        },
        flags: [
          { flag: "-p, --project <name>", desc: "Specify project name for command" },
          { flag: "-j, --json", desc: "Output as JSON instead of formatted text" },
          { flag: "-q, --quiet", desc: "Suppress non-error output" },
          { flag: "-v, --verbose", desc: "Show detailed output" },
          { flag: "--help", desc: "Show help for current command" },
          { flag: "--version", desc: "Show CLI version" },
        ],
      },
      integrations: {
        title: "Integrations",
        description: "Connect GitLuma with your favorite tools and services.",
        sections: [
          { id: "github-oauth", label: "GitHub OAuth" },
          { id: "webhook-setup", label: "Webhook Setup" },
          { id: "socket-events", label: "Socket Events" },
          { id: "cicd-integration", label: "CI/CD Integration" },
        ],
        activeStatus: "Active",
        featuresLabel: "Features:",
        githubOAuthTitle: "GitHub OAuth",
        githubOAuthIntro: "GitLuma seamlessly integrates with GitHub for automatic webhook setup and authentication.",
        githubFeatures: [
          "Automatic webhook registration",
          "OAuth authentication",
          "Real-time commit tracking",
          "PR and issue notifications",
          "Branch protection support",
        ],
        setupInstructionsTitle: "Setup Instructions:",
        webhookSetupTitle: "Webhook Setup",
        webhookSetupIntro: "Automatically configured when you initialize a project, but you can set it up manually:",
        webhookPayloadTitle: "Webhook Payload Example:",
        socketEventsTitle: "Socket Events",
        socketEventsIntro: "GitLuma streams live notifications and commit activity over Socket.IO so dashboards update without refreshing.",
        cicdTitle: "CI/CD Integration",
        cicdIntro: "Connect GitLuma to your pipeline to verify builds, tag releases and keep project activity visible after every deployment.",
        availableIntegrationsTitle: "Available Integrations",
        integrationCards: [
          { name: "Slack", description: "Get notifications in your Slack workspace", features: ["Commit notifications", "Team mentions", "Custom channels", "Digest mode"], color: "#3A7EE8" },
          { name: "Discord", description: "Send GitLuma updates to your Discord server", features: ["Webhooks support", "Mention members", "Embed formatting", "Channel routing"], color: "#7289DA" },
          { name: "Microsoft Teams", description: "Integrate with Microsoft Teams for notifications", features: ["Adaptive cards", "Channel posts", "Rich formatting", "User mentions"], color: "#0078D4" },
          { name: "Zapier", description: "Automate workflows with Zapier", features: ["Trigger actions", "Multi-app support", "Custom workflows", "Schedule actions"], color: "#FF6B2A" },
          { name: "Jira", description: "Sync commits with Jira issues", features: ["Auto-linking", "Commit comments", "Issue updates", "Time tracking"], color: "#0052CC" },
          { name: "Linear", description: "Track issues in Linear", features: ["Issue linking", "Status updates", "Cycle tracking", "Team sync"], color: "#6366F1" },
        ],
        comingSoonTitle: "Coming Soon",
        comingSoonLabel: "Coming Soon",
        comingSoonItems: ["GitLab", "Bitbucket", "AWS CodeBuild", "GitKraken", "Figma", "Notion"],
        envTitle: "Environment Variables",
        envIntro: "Configure integrations with environment variables:",
      },
      authentication: {
        title: "Authentication",
        description: "Secure your GitLuma account with robust authentication mechanisms.",
        sections: [
          { id: "overview", label: "Overview" },
          { id: "jwt-tokens", label: "JWT Tokens" },
          { id: "oauth-flow", label: "OAuth Flow" },
          { id: "api-keys", label: "API Keys" },
          { id: "refresh-tokens", label: "Refresh Tokens" },
        ],
        overviewTitle: "Overview",
        overviewIntro: "GitLuma combines GitHub OAuth, short-lived JWT access tokens and refresh tokens to keep the app secure while making login and API usage smooth.",
        jwtTitle: "JWT Tokens",
        jwtIntro: "Access tokens authorize protected requests, while refresh tokens are used to issue a new access token when the short-lived one expires.",
        oauthTitle: "OAuth Flow",
        oauthIntro: "GitLuma uses GitHub OAuth 2.0 for secure authentication:",
        oauthSteps: [
          { title: "User initiates login", desc: 'User clicks "Login with GitHub" button' },
          { title: "Redirected to GitHub", desc: "User authorizes GitLuma to access their account" },
          { title: "Authorization code received", desc: "GitHub redirects back with authorization code" },
          { title: "Access token issued", desc: "GitLuma backend exchanges code for access token" },
          { title: "User authenticated", desc: "User session created and stored securely" },
        ],
        apiKeysTitle: "API Keys",
        apiKeysIntro: "For API access and CLI usage, generate personal access tokens in your profile settings.",
        generatingTitle: "Generating a Token:",
        generatingSteps: [
          "1. Go to your Profile Settings",
          '2. Click "API Tokens" in the sidebar',
          '3. Click "Generate New Token"',
          "4. Set token name and expiration (optional)",
          "5. Copy and store securely - you will not see it again!",
        ],
        usingTitle: "Using a Token:",
        refreshTitle: "Refresh Tokens",
        refreshIntro: "The client can exchange a valid refresh token for a new access token without forcing the user through login again.",
        tokenScopesTitle: "Token Scopes",
        scopes: [
          { code: "read:projects", meaning: "List and view project details" },
          { code: "write:projects", meaning: "Create, update, and delete projects" },
          { code: "read:commits", meaning: "View commit history and statistics" },
          { code: "read:members", meaning: "View project team members" },
          { code: "write:members", meaning: "Manage project members and invites" },
          { code: "admin:webhooks", meaning: "Manage webhooks and integrations" },
        ],
        bestPracticesTitle: "Security Best Practices",
        bestPractices: [
          { title: "Never share tokens", desc: "Treat tokens like passwords. Never commit them to version control or share them publicly." },
          { title: "Rotate regularly", desc: "Generate new tokens periodically and revoke old ones. Set expiration dates on tokens." },
          { title: "Use minimal scopes", desc: "Grant only the scopes your application needs. Avoid using full admin scopes." },
          { title: "Monitor activity", desc: "Check your security log for unauthorized access or suspicious activity." },
          { title: "Enable 2FA", desc: "Enable two-factor authentication on your GitHub and GitLuma accounts." },
        ],
        revokeTitle: "Revoking Tokens",
        revokeIntro: "To revoke a token:",
        revokeSteps: [
          "1. Go to Profile Settings -> API Tokens",
          "2. Find the token you want to revoke",
          '3. Click the "Revoke" button',
          "4. Confirm the action",
        ],
        revokeWarning: "Warning: Revoking a token will immediately invalidate all API calls using it.",
      },
      sdk: {
        title: "SDK",
        description: "Integrate GitLuma into your applications with our official SDKs and libraries.",
        sections: [
          { id: "installation", label: "Installation" },
          { id: "quick-start", label: "Quick Start" },
          { id: "projects-api", label: "Projects API" },
          { id: "commits-api", label: "Commits API" },
          { id: "typescript-types", label: "TypeScript Types" },
        ],
        javascriptSdkTitle: "JavaScript SDK",
        installationTitle: "Installation",
        quickStartTitle: "Quick Start",
        projectsApiTitle: "Projects API",
        commitsApiTitle: "Commits API",
        membersApiTitle: "Members API",
        reactHooksTitle: "React Hooks",
        reactHooksIntro: "Use the official React hooks to integrate GitLuma data into your components.",
        useProjectsTitle: "useProjects Hook",
        useCommitsTitle: "useCommits Hook",
        providerTitle: "useGitLuma Provider",
        typescriptTitle: "TypeScript Types",
        typescriptIntro: "Full TypeScript support with types included. No need for separate @types packages.",
        errorHandlingTitle: "Error Handling",
        commonErrorCodesTitle: "Common Error Codes",
        errorCodes: [
          { code: "NOT_FOUND", meaning: "Resource not found (404)" },
          { code: "UNAUTHORIZED", meaning: "Invalid or missing authentication (401)" },
          { code: "FORBIDDEN", meaning: "Insufficient permissions (403)" },
          { code: "RATE_LIMITED", meaning: "Rate limit exceeded (429)" },
          { code: "SERVER_ERROR", meaning: "Internal server error (500)" },
        ],
        cachingTitle: "Caching",
        paginationTitle: "Pagination",
        examplesTitle: "Examples",
        dashboardTitle: "Build a commit dashboard",
        reportTitle: "Generate team report",
        supportTitle: "Support & Docs",
        supportLinks: [
          { title: "Full API Docs", desc: "Complete SDK reference with all methods and types" },
          { title: "Community Support", desc: "Get help from our community on Discord" },
        ],
      },
    },
  },
  uz: {
    common: {
      docsBadge: "Docs",
      documentation: "Hujjatlar",
      gitLumaDocs: "GitLuma Docs",
      home: "Bosh sahifa",
      backToHome: "Bosh sahifaga qaytish",
      backToDocs: "Hujjatlarga qaytish",
      allDocs: "Barcha hujjatlar",
      onThisPage: "Shu sahifada",
      navigate: "O'tish",
      searchDocs: "Hujjatlardan qidirish...",
      statusLive: "v2.0 - Faol",
      lastUpdated: "Oxirgi yangilanish: Aprel 2026",
      copy: "Nusxa olish",
      copied: "Nusxa olindi!",
      closeDocsNavigation: "Hujjatlar navigatsiyasini yopish",
      closeNavigation: "Navigatsiyani yopish",
      themeLight: "Yorug' rejim",
      themeDark: "Qorong'i rejim",
      linkedTopic: "Landing pagedan bog'langan hujjat mavzusi",
    },
    nav: [
      {
        id: "getting-started",
        label: "Boshlash",
        path: "/docs/getting-started",
        sections: [
          { id: "installation", label: "O'rnatish" },
          { id: "quick-start-in-3-steps", label: "3 qadamda tez boshlash" },
          { id: "system-requirements", label: "Tizim talablari" },
          { id: "troubleshooting", label: "Muammolarni hal qilish" },
        ],
      },
      {
        id: "api-reference",
        label: "API ma'lumotnomasi",
        path: "/docs/api-reference",
        sections: [
          { id: "base-url", label: "Asosiy URL" },
          { id: "authentication", label: "Autentifikatsiya" },
          { id: "projects", label: "Loyihalar" },
          { id: "commits", label: "Commitlar" },
          { id: "invites", label: "Takliflar" },
          { id: "webhooks", label: "Webhooklar" },
          { id: "error-codes", label: "Xato kodlari" },
        ],
      },
      {
        id: "cli",
        label: "CLI vositasi",
        path: "/docs/cli-tool",
        sections: [
          { id: "installation", label: "O'rnatish" },
          { id: "core-commands", label: "Asosiy buyruqlar" },
          { id: "project-management", label: "Loyiha boshqaruvi" },
          { id: "configuration", label: "Sozlamalar" },
          { id: "flags-options", label: "Flaglar va opsiyalar" },
        ],
      },
      {
        id: "integrations",
        label: "Integratsiyalar",
        path: "/docs/integrations",
        sections: [
          { id: "github-oauth", label: "GitHub OAuth" },
          { id: "webhook-setup", label: "Webhook sozlash" },
          { id: "socket-events", label: "Socket hodisalari" },
          { id: "cicd-integration", label: "CI/CD integratsiyasi" },
        ],
      },
      {
        id: "auth",
        label: "Autentifikatsiya",
        path: "/docs/authentication",
        sections: [
          { id: "overview", label: "Umumiy ko'rinish" },
          { id: "jwt-tokens", label: "JWT tokenlar" },
          { id: "oauth-flow", label: "OAuth oqimi" },
          { id: "api-keys", label: "API kalitlar" },
          { id: "refresh-tokens", label: "Yangilash tokenlari" },
        ],
      },
      {
        id: "sdk",
        label: "SDK",
        path: "/docs/sdk",
        sections: [
          { id: "installation", label: "O'rnatish" },
          { id: "quick-start", label: "Tez boshlash" },
          { id: "projects-api", label: "Projects API" },
          { id: "commits-api", label: "Commits API" },
          { id: "typescript-types", label: "TypeScript turlari" },
        ],
      },
    ],
    hub: {
      title: "GitLuma hujjatlari",
      description: "GitHub ulash, ish oqimlarini avtomatlashtirish va jamoa commitlarini real vaqtda kuzatish uchun kerak bo'ladigan hamma narsa shu yerda.",
      primaryCta: "Boshlash",
      secondaryCta: "API ma'lumotnomasi",
      stats: [
        { end: 99, suffix: "%", label: "Uptime SLA" },
        { end: 500, suffix: "ms", label: "O'rtacha javob" },
        { end: 12, suffix: "k+", label: "API chaqiruv/min" },
      ],
      quickStartTitle: "Tez boshlash",
      quickCards: [
        { id: "install-cli", title: "CLI o'rnatish", desc: "GitLuma CLI'ni 60 soniyadan kam vaqtda sozlang.", href: "/docs/cli-tool", color: "#E8654A" },
        { id: "connect-github", title: "GitHub ulash", desc: "Bir bosishda OAuth va webhook sozlash.", href: "/docs/getting-started", color: "#3A7EE8" },
        { id: "api-keys", title: "API kalitlar", desc: "Shaxsiy access tokenlarni yarating va boshqaring.", href: "/docs/authentication", color: "#22B07D" },
        { id: "sdk-reference", title: "SDK ma'lumotnomasi", desc: "To'liq turlar bilan JavaScript va TypeScript SDK.", href: "/docs/sdk", color: "#9B59B6" },
        { id: "guides", title: "Qo'llanmalar", desc: "Keng tarqalgan ish oqimlari uchun bosqichma-bosqich yo'riqnoma.", href: "/docs/getting-started", color: "#F39C12" },
        { id: "rest-api", title: "REST API", desc: "OpenAPI 3.0 sxemasi bilan to'liq REST API.", href: "/docs/api-reference", color: "#E84A7A" },
      ],
      featureGuidesTitle: "Funksiya qo'llanmalari",
      featureGuides: [
        {
          id: "real-time-notifications",
          title: "Real vaqt bildirishnomalari",
          summary: "GitLuma commit, branch va faoliyat hodisalarini WebSocket orqali UI'ga darhol uzatadi, shuning uchun jamoa yangi ishni sahifani yangilamasdan ko'radi.",
          bullets: [
            "Push hodisalari har bir ulangan loyiha a'zosiga real vaqtda yuboriladi.",
            "Presence va activity kartalari polling'siz sinxron qoladi.",
            "Trafik tez va aniq bo'lishi uchun loyiha bo'yicha obuna bo'lish mumkin.",
          ],
          language: "javascript",
          code: `const socket = io("wss://api.gitluma.io");\n\nsocket.emit("project:subscribe", {\n  projectId: "my-awesome-app",\n});\n\nsocket.on("commit:created", (event) => {\n  console.log(event.message, event.author, event.timestamp);\n});`,
        },
        {
          id: "github-integration",
          title: "GitHub integratsiyasi",
          summary: "Repository'ni bir marta ulang, qolgan webhook yaratish, repo ruxsatlari va commitlarni qabul qilishni GitLuma avtomatik bajaradi.",
          bullets: [
            "OAuth ulanish tanlangan GitHub akkauntini xavfsiz bog'laydi.",
            "Webhook sozlamasi loyiha yaratish vaqtida qo'shiladi.",
            "Branch, PR havolalari va commit metadata dashboardga sinxronlanadi.",
          ],
          language: "bash",
          code: `gitluma auth login\n# Authorize GitHub access in the browser\n\ngitluma init\n# Repository linked and webhook configured automatically`,
        },
        {
          id: "team-collaboration",
          title: "Jamoaviy hamkorlik",
          summary: "Loyihalar live presence, rollarga asoslangan ruxsat va vazifa ko'rinishi bilan umumiy workspace'larni qo'llaydi, shuning uchun hamma kim nima qilayotganini ko'radi.",
          bullets: [
            "Owner'lar a'zolarni taklif qilishi va loyiha kirishini boshqarishi mumkin.",
            "A'zolar faolligi, joriy vazifalar va oxirgi ishlar bitta joyda ko'rinadi.",
            "Umumiy board'lar dizayn, kod va review'ni muvofiqlashtirishni osonlashtiradi.",
          ],
          language: "json",
          code: `{\n  "project": "my-awesome-app",\n  "members": [\n    { "name": "Ali", "role": "owner", "status": "online" },\n    { "name": "Maya", "role": "member", "status": "reviewing" }\n  ],\n  "liveBoard": true\n}`,
        },
        {
          id: "email-invitations",
          title: "Email takliflar",
          summary: "Jamoa a'zolarini email orqali qo'shilish havolasi, avtomatik loyiha biriktirish va kerak bo'lsa qayta yuborish yoki bekor qilish imkoniyati bilan taklif qiling.",
          bullets: [
            "Har bir taklif loyiha va rolga bog'lanadi.",
            "Qabul qilingan taklif foydalanuvchini to'g'ridan-to'g'ri workspace'ga qo'shadi.",
            "Kutilayotgan takliflarni bir joydan qayta yuborish, bekor qilish yoki audit qilish mumkin.",
          ],
          language: "javascript",
          code: `await fetch("https://api.gitluma.io/api/invites", {\n  method: "POST",\n  headers: {\n    Authorization: "Bearer YOUR_TOKEN",\n    "Content-Type": "application/json",\n  },\n  body: JSON.stringify({\n    email: "alex@team.dev",\n    projectId: "my-awesome-app",\n    role: "member",\n  }),\n});`,
        },
      ],
      installation: {
        title: "O'rnatish",
        intro: "GitLuma CLI'ni npm yoki yarn orqali global o'rnating:",
        authTitle: "GitHub orqali kirish",
        projectTitle: "Loyihani ishga tushirish",
      },
      apiReference: {
        title: "API ma'lumotnomasi",
        endpoints: [
          { method: "GET", path: "/api/projects", desc: "Autentifikatsiyalangan foydalanuvchi uchun barcha loyihalarni chiqaradi", color: "#22B07D" },
          { method: "POST", path: "/api/projects", desc: "Repository'ga bog'langan yangi loyiha yaratadi", color: "#3A7EE8" },
          { method: "GET", path: "/api/projects/:id", desc: "ID bo'yicha loyiha tafsilotlarini qaytaradi", color: "#22B07D" },
          { method: "DELETE", path: "/api/projects/:id", desc: "Loyihani o'chiradi va webhook'ni uzadi", color: "#E84A7A" },
          { method: "GET", path: "/api/commits/:projId", desc: "Loyiha uchun sahifalangan commit tarixini qaytaradi", color: "#22B07D" },
          { method: "POST", path: "/api/invites", desc: "Loyihaga qo'shilish uchun email taklif yuboradi", color: "#3A7EE8" },
        ],
        exampleTitle: "So'rov namunasi",
      },
      webhooks: {
        title: "Webhooklar",
        intro: "GitLuma GitHub repo'da webhook'ni avtomatik ro'yxatdan o'tkazadi. Xohlasangiz uni qo'lda ham kiritishingiz mumkin:",
      },
    },
    pages: {
      gettingStarted: {
        title: "Boshlash",
        description: "Bir necha daqiqada GitLuma bilan ishni boshlang. Asoslarni o'rganing va birinchi loyihangizni sozlang.",
        sections: [
          { id: "installation", label: "O'rnatish" },
          { id: "quick-start-in-3-steps", label: "3 qadamda tez boshlash" },
          { id: "system-requirements", label: "Tizim talablari" },
          { id: "troubleshooting", label: "Muammolarni hal qilish" },
        ],
        installationTitle: "O'rnatish",
        installationIntro: "GitLuma CLI'ni npm yoki yarn orqali global o'rnating:",
        quickStartTitle: "3 qadamda tez boshlash",
        quickStartSteps: [
          { title: "1-qadam: Kirish", desc: "GitHub akkauntingizni OAuth orqali xavfsiz ulang" },
          { title: "2-qadam: Loyihani ulash", desc: "Repository'ingizni GitLuma bilan bog'lang" },
          { title: "3-qadam: Kuzatishni boshlash", desc: "Commit va jamoa faolligini real vaqtda ko'ring" },
        ],
        authenticateTitle: "GitHub orqali kirish",
        systemRequirementsTitle: "Tizim talablari",
        minimumTitle: "Minimal",
        minimumItems: ["Node.js 14.0+", "npm 6.0+ yoki yarn 1.22+", "Git 2.0+"],
        recommendedTitle: "Tavsiya etiladi",
        recommendedItems: ["Node.js 18.0+", "So'nggi npm yoki yarn", "GitHub Enterprise qo'llovi"],
        troubleshootingTitle: "Muammolarni hal qilish",
        commandNotFoundTitle: "Buyruq topilmadi",
        authFailedTitle: "Autentifikatsiya muvaffaqiyatsiz bo'ldi",
        authFailedIntro: "Auth keshini tozalab, qayta urinib ko'ring:",
      },
      apiReference: {
        title: "API ma'lumotnomasi",
        description: "GitLuma'ni ilovalaringizga ulash uchun to'liq API hujjatlari.",
        sections: [
          { id: "base-url", label: "Asosiy URL" },
          { id: "authentication", label: "Autentifikatsiya" },
          { id: "projects", label: "Loyihalar" },
          { id: "commits", label: "Commitlar" },
          { id: "invites", label: "Takliflar" },
          { id: "webhooks", label: "Webhooklar" },
          { id: "error-codes", label: "Xato kodlari" },
        ],
        exampleRequest: "So'rov namunasi:",
        response: "Javob:",
        baseUrlTitle: "Asosiy URL",
        baseUrlIntro: "Barcha REST so'rovlar GitLuma API asosiy URL manziliga yuborilishi kerak.",
        authenticationTitle: "Autentifikatsiya",
        authenticationIntro: "Barcha API so'rovlar Bearer tokenlar orqali autentifikatsiyani talab qiladi:",
        endpointsTitle: "Endpointlar",
        projectsTitle: "Loyihalar",
        commitsTitle: "Commitlar",
        invitesTitle: "Takliflar",
        webhooksTitle: "Webhooklar",
        webhooksIntro: "Commit faolligini GitLuma'ga real vaqtda uzatish uchun GitHub webhooklaridan foydalaning.",
        errorCodesTitle: "Xato kodlari",
        errorCodesIntro: "API xatolari standart HTTP status kodlari bilan qaytadi:",
        rateLimitingTitle: "Rate limit",
        freeTierTitle: "Bepul tarif",
        freeTierDesc: "Daqiqasiga 1 000 so'rov",
        proTierTitle: "Pro tarif",
        proTierDesc: "Daqiqasiga 10 000 so'rov",
        endpoints: {
          projects: [
            { method: "GET", path: "/api/projects", desc: "Autentifikatsiyalangan foydalanuvchi uchun barcha loyihalarni chiqaradi", color: "#22B07D" },
            { method: "POST", path: "/api/projects", desc: "Repository'ga bog'langan yangi loyiha yaratadi", color: "#3A7EE8" },
            { method: "GET", path: "/api/projects/:id", desc: "ID bo'yicha loyiha tafsilotlarini qaytaradi", color: "#22B07D" },
          ],
          commits: [
            { method: "GET", path: "/api/commits/:projId", desc: "Loyiha uchun sahifalangan commit tarixini qaytaradi", color: "#22B07D" },
          ],
          invites: [
            { method: "POST", path: "/api/invites", desc: "Loyihaga qo'shilish uchun email taklif yuboradi", color: "#3A7EE8" },
          ],
        },
      },
      cliTool: {
        title: "CLI vositasi",
        description: "Loyihalarni boshqarish va commitlarni kuzatish uchun GitLuma buyruq satri interfeysini puxta o'zlashtiring.",
        sections: [
          { id: "installation", label: "O'rnatish" },
          { id: "core-commands", label: "Asosiy buyruqlar" },
          { id: "project-management", label: "Loyiha boshqaruvi" },
          { id: "configuration", label: "Sozlamalar" },
          { id: "flags-options", label: "Flaglar va opsiyalar" },
        ],
        output: "Natija:",
        installationTitle: "O'rnatish",
        coreCommandsTitle: "Asosiy buyruqlar",
        authenticationTitle: "Autentifikatsiya",
        projectManagementTitle: "Loyiha boshqaruvi",
        teamManagementTitle: "Jamoa boshqaruvi",
        commitsTrackingTitle: "Commitlar va kuzatish",
        configurationTitle: "Sozlamalar",
        configFileTitle: "Config fayli",
        configFileIntro: "CLI sozlamalaringiz quyidagi joyda saqlanadi:",
        flagsTitle: "Flaglar va opsiyalar",
        tipsTitle: "Maslahatlar",
        useAliasesTitle: "Aliaslardan foydalaning",
        automatedSetupTitle: "Avtomatik sozlash",
        commands: {
          authLogin: "GitHub akkauntingiz orqali kirish",
          authLogout: "Tizimdan chiqish va saqlangan ma'lumotlarni olib tashlash",
          authStatus: "Joriy autentifikatsiya holatini tekshirish",
          init: "Joriy repo ichida GitLuma loyihasini ishga tushirish",
          projectsList: "Barcha loyihalaringizni ko'rsatish",
          projectsInfo: "Loyiha haqida batafsil ma'lumot olish",
          invite: "Jamoa a'zosini loyihaga taklif qilish",
          membersList: "Loyiha a'zolarini ko'rsatish",
          commitsList: "Loyihadagi so'nggi commitlarni ko'rish",
          commitsStats: "Commit statistikalarini olish",
        },
        flags: [
          { flag: "-p, --project <name>", desc: "Buyruq uchun loyiha nomini ko'rsatish" },
          { flag: "-j, --json", desc: "Formatlangan matn o'rniga JSON chiqish" },
          { flag: "-q, --quiet", desc: "Xatodan tashqari chiqishni yashirish" },
          { flag: "-v, --verbose", desc: "Batafsil natija ko'rsatish" },
          { flag: "--help", desc: "Joriy buyruq uchun yordamni ko'rsatish" },
          { flag: "--version", desc: "CLI versiyasini ko'rsatish" },
        ],
      },
      integrations: {
        title: "Integratsiyalar",
        description: "GitLuma'ni sevimli servis va vositalaringiz bilan ulang.",
        sections: [
          { id: "github-oauth", label: "GitHub OAuth" },
          { id: "webhook-setup", label: "Webhook sozlash" },
          { id: "socket-events", label: "Socket hodisalari" },
          { id: "cicd-integration", label: "CI/CD integratsiyasi" },
        ],
        activeStatus: "Faol",
        featuresLabel: "Imkoniyatlar:",
        githubOAuthTitle: "GitHub OAuth",
        githubOAuthIntro: "GitLuma GitHub bilan uzluksiz ulanib, webhook sozlash va autentifikatsiyani avtomatik bajaradi.",
        githubFeatures: [
          "Webhooklarni avtomatik ro'yxatdan o'tkazish",
          "OAuth autentifikatsiyasi",
          "Commitlarni real vaqtda kuzatish",
          "PR va issue bildirishnomalari",
          "Branch protection qo'llovi",
        ],
        setupInstructionsTitle: "Sozlash bo'yicha ko'rsatmalar:",
        webhookSetupTitle: "Webhook sozlash",
        webhookSetupIntro: "Loyiha ishga tushirilganda avtomatik sozlanadi, lekin xohlasangiz qo'lda ham sozlashingiz mumkin:",
        webhookPayloadTitle: "Webhook payload namunasi:",
        socketEventsTitle: "Socket hodisalari",
        socketEventsIntro: "GitLuma live bildirishnoma va commit faolligini Socket.IO orqali uzatadi, shu sabab dashboard yangilashsiz ishlaydi.",
        cicdTitle: "CI/CD integratsiyasi",
        cicdIntro: "Buildlarni tekshirish, release'larni belgilash va deploydan keyin loyiha faolligini ko'rinadigan qilish uchun GitLuma'ni pipeline'ga ulang.",
        availableIntegrationsTitle: "Mavjud integratsiyalar",
        integrationCards: [
          { name: "Slack", description: "Slack workspace'ingizga bildirishnomalar yuboring", features: ["Commit bildirishnomalari", "Jamoa mentionlari", "Maxsus kanallar", "Digest rejimi"], color: "#3A7EE8" },
          { name: "Discord", description: "GitLuma yangilanishlarini Discord serverga yuboring", features: ["Webhook qo'llovi", "A'zolarni mention qilish", "Embed format", "Kanal routing"], color: "#7289DA" },
          { name: "Microsoft Teams", description: "Bildirishnomalar uchun Microsoft Teams bilan integratsiya", features: ["Adaptive cardlar", "Kanalga post", "Rich format", "Foydalanuvchi mentionlari"], color: "#0078D4" },
          { name: "Zapier", description: "Zapier bilan ish oqimlarini avtomatlashtiring", features: ["Trigger actionlar", "Ko'p ilova qo'llovi", "Custom workflow", "Jadval bo'yicha ish"], color: "#FF6B2A" },
          { name: "Jira", description: "Commitlarni Jira issue'lari bilan sinxronlang", features: ["Avto bog'lash", "Commit commentlar", "Issue yangilanishlari", "Time tracking"], color: "#0052CC" },
          { name: "Linear", description: "Issue'larni Linear'da kuzating", features: ["Issue bog'lash", "Status yangilanishlari", "Cycle tracking", "Team sync"], color: "#6366F1" },
        ],
        comingSoonTitle: "Tez orada",
        comingSoonLabel: "Tez orada",
        comingSoonItems: ["GitLab", "Bitbucket", "AWS CodeBuild", "GitKraken", "Figma", "Notion"],
        envTitle: "Muhit o'zgaruvchilari",
        envIntro: "Integratsiyalarni environment variable'lar bilan sozlang:",
      },
      authentication: {
        title: "Autentifikatsiya",
        description: "GitLuma akkauntingizni mustahkam autentifikatsiya mexanizmlari bilan himoya qiling.",
        sections: [
          { id: "overview", label: "Umumiy ko'rinish" },
          { id: "jwt-tokens", label: "JWT tokenlar" },
          { id: "oauth-flow", label: "OAuth oqimi" },
          { id: "api-keys", label: "API kalitlar" },
          { id: "refresh-tokens", label: "Yangilash tokenlari" },
        ],
        overviewTitle: "Umumiy ko'rinish",
        overviewIntro: "GitLuma GitHub OAuth, qisqa muddatli JWT access tokenlar va refresh tokenlarni birlashtirib, kirish va API foydalanishni qulay ham xavfsiz qiladi.",
        jwtTitle: "JWT tokenlar",
        jwtIntro: "Access tokenlar himoyalangan so'rovlarni tasdiqlaydi, refresh tokenlar esa qisqa muddatli access token muddati tugaganda yangisini olish uchun ishlatiladi.",
        oauthTitle: "OAuth oqimi",
        oauthIntro: "GitLuma xavfsiz autentifikatsiya uchun GitHub OAuth 2.0 dan foydalanadi:",
        oauthSteps: [
          { title: "Foydalanuvchi kirishni boshlaydi", desc: 'Foydalanuvchi "Login with GitHub" tugmasini bosadi' },
          { title: "GitHub'ga yo'naltiriladi", desc: "Foydalanuvchi GitLuma'ga akkauntiga kirish ruxsatini beradi" },
          { title: "Authorization code olinadi", desc: "GitHub authorization code bilan qayta yo'naltiradi" },
          { title: "Access token beriladi", desc: "GitLuma backend code'ni access token'ga almashtiradi" },
          { title: "Foydalanuvchi autentifikatsiya qilinadi", desc: "Sessiya yaratiladi va xavfsiz saqlanadi" },
        ],
        apiKeysTitle: "API kalitlar",
        apiKeysIntro: "API va CLI orqali foydalanish uchun profil sozlamalarida shaxsiy access tokenlar yarating.",
        generatingTitle: "Token yaratish:",
        generatingSteps: [
          "1. Profil sozlamalariga o'ting",
          '2. Yon panelda "API Tokens" ni bosing',
          '3. "Generate New Token" ni bosing',
          "4. Token nomi va amal qilish muddatini belgilang (ixtiyoriy)",
          "5. Nusxa oling va xavfsiz saqlang - u keyin yana ko'rinmaydi!",
        ],
        usingTitle: "Token ishlatish:",
        refreshTitle: "Yangilash tokenlari",
        refreshIntro: "Mijoz foydalanuvchini qayta login qildirmasdan, amaldagi refresh token orqali yangi access token olishi mumkin.",
        tokenScopesTitle: "Token scope'lari",
        scopes: [
          { code: "read:projects", meaning: "Loyiha tafsilotlarini ko'rish va ro'yxatlash" },
          { code: "write:projects", meaning: "Loyihalarni yaratish, yangilash va o'chirish" },
          { code: "read:commits", meaning: "Commit tarixi va statistikani ko'rish" },
          { code: "read:members", meaning: "Loyiha a'zolarini ko'rish" },
          { code: "write:members", meaning: "A'zolar va takliflarni boshqarish" },
          { code: "admin:webhooks", meaning: "Webhook va integratsiyalarni boshqarish" },
        ],
        bestPracticesTitle: "Xavfsizlik bo'yicha tavsiyalar",
        bestPractices: [
          { title: "Tokenlarni ulashmang", desc: "Tokenlarga paroldek qarang. Ularni version control'ga commit qilmang va omma oldida ulashmang." },
          { title: "Muntazam almashtiring", desc: "Yangi tokenlarni davriy yarating va eskilarini bekor qiling. Amal qilish muddatini belgilang." },
          { title: "Minimal scope'dan foydalaning", desc: "Ilovangizga kerak bo'lgan ruxsatlarnigina bering. To'liq admin scope'laridan qoching." },
          { title: "Faollikni kuzating", desc: "Ruxsatsiz kirish yoki shubhali faollik uchun security log'ni tekshirib turing." },
          { title: "2FA'ni yoqing", desc: "GitHub va GitLuma akkauntlaringizda ikki bosqichli himoyani yoqing." },
        ],
        revokeTitle: "Tokenlarni bekor qilish",
        revokeIntro: "Tokenni bekor qilish uchun:",
        revokeSteps: [
          "1. Profil sozlamalari -> API Tokens bo'limiga o'ting",
          "2. Bekor qilmoqchi bo'lgan tokenni toping",
          '3. "Revoke" tugmasini bosing',
          "4. Amalni tasdiqlang",
        ],
        revokeWarning: "Ogohlantirish: tokenni bekor qilish u bilan ishlayotgan barcha API so'rovlarni darhol yaroqsiz qiladi.",
      },
      sdk: {
        title: "SDK",
        description: "Rasmiy SDK va kutubxonalar orqali GitLuma'ni ilovalaringizga ulang.",
        sections: [
          { id: "installation", label: "O'rnatish" },
          { id: "quick-start", label: "Tez boshlash" },
          { id: "projects-api", label: "Projects API" },
          { id: "commits-api", label: "Commits API" },
          { id: "typescript-types", label: "TypeScript turlari" },
        ],
        javascriptSdkTitle: "JavaScript SDK",
        installationTitle: "O'rnatish",
        quickStartTitle: "Tez boshlash",
        projectsApiTitle: "Projects API",
        commitsApiTitle: "Commits API",
        membersApiTitle: "Members API",
        reactHooksTitle: "React hooklar",
        reactHooksIntro: "GitLuma ma'lumotlarini komponentlarga ulash uchun rasmiy React hooklaridan foydalaning.",
        useProjectsTitle: "useProjects hook",
        useCommitsTitle: "useCommits hook",
        providerTitle: "useGitLuma Provider",
        typescriptTitle: "TypeScript turlari",
        typescriptIntro: "TypeScript to'liq qo'llanadi va turlar ichida keladi. Alohida @types paket kerak emas.",
        errorHandlingTitle: "Xatolarni boshqarish",
        commonErrorCodesTitle: "Keng tarqalgan xato kodlari",
        errorCodes: [
          { code: "NOT_FOUND", meaning: "Resurs topilmadi (404)" },
          { code: "UNAUTHORIZED", meaning: "Autentifikatsiya noto'g'ri yoki yo'q (401)" },
          { code: "FORBIDDEN", meaning: "Ruxsat yetarli emas (403)" },
          { code: "RATE_LIMITED", meaning: "Rate limit oshib ketdi (429)" },
          { code: "SERVER_ERROR", meaning: "Ichki server xatosi (500)" },
        ],
        cachingTitle: "Kesh",
        paginationTitle: "Sahifalash",
        examplesTitle: "Misollar",
        dashboardTitle: "Commit dashboard qurish",
        reportTitle: "Jamoa hisobotini yaratish",
        supportTitle: "Yordam va hujjatlar",
        supportLinks: [
          { title: "To'liq API hujjatlari", desc: "Barcha metod va turlar bilan to'liq SDK reference" },
          { title: "Hamjamiyat yordami", desc: "Discord hamjamiyatimizdan yordam oling" },
        ],
      },
    },
  },
  ru: {
    common: {
      docsBadge: "Docs",
      documentation: "Документация",
      gitLumaDocs: "GitLuma Docs",
      home: "Главная",
      backToHome: "Назад на главную",
      backToDocs: "Назад к документации",
      allDocs: "Все документы",
      onThisPage: "На этой странице",
      navigate: "Переход",
      searchDocs: "Поиск по документации...",
      statusLive: "v2.0 - Активно",
      lastUpdated: "Последнее обновление: Апрель 2026",
      copy: "Копировать",
      copied: "Скопировано!",
      closeDocsNavigation: "Закрыть навигацию документации",
      closeNavigation: "Закрыть навигацию",
      themeLight: "Светлая тема",
      themeDark: "Темная тема",
      linkedTopic: "Раздел документации, связанный с landing page",
    },
    nav: [
      {
        id: "getting-started",
        label: "Быстрый старт",
        path: "/docs/getting-started",
        sections: [
          { id: "installation", label: "Установка" },
          { id: "quick-start-in-3-steps", label: "Быстрый старт за 3 шага" },
          { id: "system-requirements", label: "Системные требования" },
          { id: "troubleshooting", label: "Решение проблем" },
        ],
      },
      {
        id: "api-reference",
        label: "Справочник API",
        path: "/docs/api-reference",
        sections: [
          { id: "base-url", label: "Базовый URL" },
          { id: "authentication", label: "Аутентификация" },
          { id: "projects", label: "Проекты" },
          { id: "commits", label: "Коммиты" },
          { id: "invites", label: "Приглашения" },
          { id: "webhooks", label: "Вебхуки" },
          { id: "error-codes", label: "Коды ошибок" },
        ],
      },
      {
        id: "cli",
        label: "CLI инструмент",
        path: "/docs/cli-tool",
        sections: [
          { id: "installation", label: "Установка" },
          { id: "core-commands", label: "Основные команды" },
          { id: "project-management", label: "Управление проектом" },
          { id: "configuration", label: "Конфигурация" },
          { id: "flags-options", label: "Флаги и опции" },
        ],
      },
      {
        id: "integrations",
        label: "Интеграции",
        path: "/docs/integrations",
        sections: [
          { id: "github-oauth", label: "GitHub OAuth" },
          { id: "webhook-setup", label: "Настройка вебхука" },
          { id: "socket-events", label: "Socket события" },
          { id: "cicd-integration", label: "CI/CD интеграция" },
        ],
      },
      {
        id: "auth",
        label: "Аутентификация",
        path: "/docs/authentication",
        sections: [
          { id: "overview", label: "Обзор" },
          { id: "jwt-tokens", label: "JWT токены" },
          { id: "oauth-flow", label: "OAuth поток" },
          { id: "api-keys", label: "API ключи" },
          { id: "refresh-tokens", label: "Refresh токены" },
        ],
      },
      {
        id: "sdk",
        label: "SDK",
        path: "/docs/sdk",
        sections: [
          { id: "installation", label: "Установка" },
          { id: "quick-start", label: "Быстрый старт" },
          { id: "projects-api", label: "Projects API" },
          { id: "commits-api", label: "Commits API" },
          { id: "typescript-types", label: "Типы TypeScript" },
        ],
      },
    ],
    hub: {
      title: "Документация GitLuma",
      description: "Все, что нужно для подключения GitHub, автоматизации процессов и отслеживания коммитов команды в реальном времени.",
      primaryCta: "Начать",
      secondaryCta: "Справочник API",
      stats: [
        { end: 99, suffix: "%", label: "Uptime SLA" },
        { end: 500, suffix: "ms", label: "Средний ответ" },
        { end: 12, suffix: "k+", label: "API вызовов/мин" },
      ],
      quickStartTitle: "Быстрый старт",
      quickCards: [
        { id: "install-cli", title: "Установить CLI", desc: "Настройте GitLuma CLI меньше чем за 60 секунд.", href: "/docs/cli-tool", color: "#E8654A" },
        { id: "connect-github", title: "Подключить GitHub", desc: "OAuth и настройка вебхука в один клик.", href: "/docs/getting-started", color: "#3A7EE8" },
        { id: "api-keys", title: "API ключи", desc: "Создавайте и управляйте персональными токенами доступа.", href: "/docs/authentication", color: "#22B07D" },
        { id: "sdk-reference", title: "Справочник SDK", desc: "JavaScript и TypeScript SDK с полными типами.", href: "/docs/sdk", color: "#9B59B6" },
        { id: "guides", title: "Гайды", desc: "Пошаговые инструкции для типовых сценариев.", href: "/docs/getting-started", color: "#F39C12" },
        { id: "rest-api", title: "REST API", desc: "Полный REST API со схемой OpenAPI 3.0.", href: "/docs/api-reference", color: "#E84A7A" },
      ],
      featureGuidesTitle: "Гайды по возможностям",
      featureGuides: [
        {
          id: "real-time-notifications",
          title: "Уведомления в реальном времени",
          summary: "GitLuma мгновенно отправляет события коммитов, веток и активности в интерфейс через WebSocket, поэтому команда видит новые изменения без обновления страницы.",
          bullets: [
            "События push передаются всем подключенным участникам проекта в реальном времени.",
            "Карточки присутствия и активности синхронизируются без polling.",
            "Можно подписываться по проекту, чтобы трафик оставался точным и быстрым.",
          ],
          language: "javascript",
          code: `const socket = io("wss://api.gitluma.io");\n\nsocket.emit("project:subscribe", {\n  projectId: "my-awesome-app",\n});\n\nsocket.on("commit:created", (event) => {\n  console.log(event.message, event.author, event.timestamp);\n});`,
        },
        {
          id: "github-integration",
          title: "Интеграция с GitHub",
          summary: "Подключите репозиторий один раз, а GitLuma сама создаст вебхук, настроит доступ и начнет принимать коммиты.",
          bullets: [
            "OAuth подключение безопасно связывает выбранный GitHub аккаунт.",
            "Вебхук создается во время инициализации проекта.",
            "Ветки, ссылки на PR и метаданные коммитов синхронизируются в дашборд.",
          ],
          language: "bash",
          code: `gitluma auth login\n# Authorize GitHub access in the browser\n\ngitluma init\n# Repository linked and webhook configured automatically`,
        },
        {
          id: "team-collaboration",
          title: "Командная работа",
          summary: "Проекты поддерживают общие рабочие пространства с live presence, ролевым доступом и видимостью задач, чтобы всем было понятно, кто чем занимается.",
          bullets: [
            "Владельцы могут приглашать участников и управлять доступом к проекту.",
            "Активность участников, текущие задачи и последняя работа видны в одном месте.",
            "Общие доски упрощают координацию дизайна, кода и review.",
          ],
          language: "json",
          code: `{\n  "project": "my-awesome-app",\n  "members": [\n    { "name": "Ali", "role": "owner", "status": "online" },\n    { "name": "Maya", "role": "member", "status": "reviewing" }\n  ],\n  "liveBoard": true\n}`,
        },
        {
          id: "email-invitations",
          title: "Приглашения по email",
          summary: "Приглашайте коллег по email с помощью ссылки на вход, автоматическим назначением проекта и возможностью повторной отправки или отзыва.",
          bullets: [
            "Каждое приглашение привязано к проекту и роли.",
            "После принятия пользователь сразу попадает в workspace.",
            "Ожидающие приглашения можно повторно отправлять, отзывать и проверять в одном списке.",
          ],
          language: "javascript",
          code: `await fetch("https://api.gitluma.io/api/invites", {\n  method: "POST",\n  headers: {\n    Authorization: "Bearer YOUR_TOKEN",\n    "Content-Type": "application/json",\n  },\n  body: JSON.stringify({\n    email: "alex@team.dev",\n    projectId: "my-awesome-app",\n    role: "member",\n  }),\n});`,
        },
      ],
      installation: {
        title: "Установка",
        intro: "Установите GitLuma CLI глобально через npm или yarn:",
        authTitle: "Вход через GitHub",
        projectTitle: "Инициализация проекта",
      },
      apiReference: {
        title: "Справочник API",
        endpoints: [
          { method: "GET", path: "/api/projects", desc: "Показать все проекты для аутентифицированного пользователя", color: "#22B07D" },
          { method: "POST", path: "/api/projects", desc: "Создать новый проект, привязанный к репозиторию", color: "#3A7EE8" },
          { method: "GET", path: "/api/projects/:id", desc: "Получить детали проекта по ID", color: "#22B07D" },
          { method: "DELETE", path: "/api/projects/:id", desc: "Удалить проект и отвязать вебхук", color: "#E84A7A" },
          { method: "GET", path: "/api/commits/:projId", desc: "Получить историю коммитов проекта с пагинацией", color: "#22B07D" },
          { method: "POST", path: "/api/invites", desc: "Отправить email приглашение в проект", color: "#3A7EE8" },
        ],
        exampleTitle: "Пример запроса",
      },
      webhooks: {
        title: "Вебхуки",
        intro: "GitLuma автоматически регистрирует вебхук в вашем GitHub репозитории. При необходимости его можно настроить вручную:",
      },
    },
    pages: {
      gettingStarted: {
        title: "Быстрый старт",
        description: "Запустите GitLuma за считанные минуты. Изучите основы и настройте свой первый проект.",
        sections: [
          { id: "installation", label: "Установка" },
          { id: "quick-start-in-3-steps", label: "Быстрый старт за 3 шага" },
          { id: "system-requirements", label: "Системные требования" },
          { id: "troubleshooting", label: "Решение проблем" },
        ],
        installationTitle: "Установка",
        installationIntro: "Установите GitLuma CLI глобально через npm или yarn:",
        quickStartTitle: "Быстрый старт за 3 шага",
        quickStartSteps: [
          { title: "Шаг 1: Аутентификация", desc: "Безопасно подключите GitHub аккаунт через OAuth" },
          { title: "Шаг 2: Инициализация проекта", desc: "Свяжите репозиторий с GitLuma" },
          { title: "Шаг 3: Начните отслеживание", desc: "Смотрите коммиты и активность команды в реальном времени" },
        ],
        authenticateTitle: "Вход через GitHub",
        systemRequirementsTitle: "Системные требования",
        minimumTitle: "Минимум",
        minimumItems: ["Node.js 14.0+", "npm 6.0+ или yarn 1.22+", "Git 2.0+"],
        recommendedTitle: "Рекомендуется",
        recommendedItems: ["Node.js 18.0+", "Последний npm или yarn", "Поддержка GitHub Enterprise"],
        troubleshootingTitle: "Решение проблем",
        commandNotFoundTitle: "Команда не найдена",
        authFailedTitle: "Ошибка аутентификации",
        authFailedIntro: "Очистите кэш аутентификации и попробуйте снова:",
      },
      apiReference: {
        title: "Справочник API",
        description: "Полная документация API для интеграции GitLuma в ваши приложения.",
        sections: [
          { id: "base-url", label: "Базовый URL" },
          { id: "authentication", label: "Аутентификация" },
          { id: "projects", label: "Проекты" },
          { id: "commits", label: "Коммиты" },
          { id: "invites", label: "Приглашения" },
          { id: "webhooks", label: "Вебхуки" },
          { id: "error-codes", label: "Коды ошибок" },
        ],
        exampleRequest: "Пример запроса:",
        response: "Ответ:",
        baseUrlTitle: "Базовый URL",
        baseUrlIntro: "Все REST запросы должны отправляться на базовый URL API GitLuma.",
        authenticationTitle: "Аутентификация",
        authenticationIntro: "Все API запросы требуют аутентификации через Bearer токены:",
        endpointsTitle: "Эндпоинты",
        projectsTitle: "Проекты",
        commitsTitle: "Коммиты",
        invitesTitle: "Приглашения",
        webhooksTitle: "Вебхуки",
        webhooksIntro: "Используйте GitHub вебхуки, чтобы передавать активность коммитов в GitLuma в реальном времени.",
        errorCodesTitle: "Коды ошибок",
        errorCodesIntro: "Ошибки API возвращают стандартные HTTP статус-коды:",
        rateLimitingTitle: "Ограничение запросов",
        freeTierTitle: "Бесплатный тариф",
        freeTierDesc: "1 000 запросов в минуту",
        proTierTitle: "Pro тариф",
        proTierDesc: "10 000 запросов в минуту",
        endpoints: {
          projects: [
            { method: "GET", path: "/api/projects", desc: "Показать все проекты для аутентифицированного пользователя", color: "#22B07D" },
            { method: "POST", path: "/api/projects", desc: "Создать новый проект, привязанный к репозиторию", color: "#3A7EE8" },
            { method: "GET", path: "/api/projects/:id", desc: "Получить детали проекта по ID", color: "#22B07D" },
          ],
          commits: [
            { method: "GET", path: "/api/commits/:projId", desc: "Получить историю коммитов проекта с пагинацией", color: "#22B07D" },
          ],
          invites: [
            { method: "POST", path: "/api/invites", desc: "Отправить email приглашение в проект", color: "#3A7EE8" },
          ],
        },
      },
      cliTool: {
        title: "CLI инструмент",
        description: "Освойте интерфейс командной строки GitLuma для управления проектами и отслеживания коммитов.",
        sections: [
          { id: "installation", label: "Установка" },
          { id: "core-commands", label: "Основные команды" },
          { id: "project-management", label: "Управление проектом" },
          { id: "configuration", label: "Конфигурация" },
          { id: "flags-options", label: "Флаги и опции" },
        ],
        output: "Вывод:",
        installationTitle: "Установка",
        coreCommandsTitle: "Основные команды",
        authenticationTitle: "Аутентификация",
        projectManagementTitle: "Управление проектом",
        teamManagementTitle: "Управление командой",
        commitsTrackingTitle: "Коммиты и отслеживание",
        configurationTitle: "Конфигурация",
        configFileTitle: "Файл конфигурации",
        configFileIntro: "Конфигурация CLI хранится здесь:",
        flagsTitle: "Флаги и опции",
        tipsTitle: "Советы",
        useAliasesTitle: "Используйте алиасы",
        automatedSetupTitle: "Автоматическая настройка",
        commands: {
          authLogin: "Аутентификация через GitHub аккаунт",
          authLogout: "Выйти и удалить сохраненные учетные данные",
          authStatus: "Проверить текущий статус аутентификации",
          init: "Инициализировать проект GitLuma в текущем репозитории",
          projectsList: "Показать все ваши проекты",
          projectsInfo: "Получить подробную информацию о проекте",
          invite: "Пригласить участника в проект",
          membersList: "Показать участников проекта",
          commitsList: "Посмотреть последние коммиты проекта",
          commitsStats: "Получить статистику по коммитам",
        },
        flags: [
          { flag: "-p, --project <name>", desc: "Указать имя проекта для команды" },
          { flag: "-j, --json", desc: "Вывести JSON вместо форматированного текста" },
          { flag: "-q, --quiet", desc: "Скрыть весь вывод кроме ошибок" },
          { flag: "-v, --verbose", desc: "Показать подробный вывод" },
          { flag: "--help", desc: "Показать справку по текущей команде" },
          { flag: "--version", desc: "Показать версию CLI" },
        ],
      },
      integrations: {
        title: "Интеграции",
        description: "Подключите GitLuma к вашим любимым сервисам и инструментам.",
        sections: [
          { id: "github-oauth", label: "GitHub OAuth" },
          { id: "webhook-setup", label: "Настройка вебхука" },
          { id: "socket-events", label: "Socket события" },
          { id: "cicd-integration", label: "CI/CD интеграция" },
        ],
        activeStatus: "Активно",
        featuresLabel: "Возможности:",
        githubOAuthTitle: "GitHub OAuth",
        githubOAuthIntro: "GitLuma легко интегрируется с GitHub для автоматической настройки вебхуков и аутентификации.",
        githubFeatures: [
          "Автоматическая регистрация вебхука",
          "OAuth аутентификация",
          "Отслеживание коммитов в реальном времени",
          "Уведомления о PR и issue",
          "Поддержка branch protection",
        ],
        setupInstructionsTitle: "Инструкция по настройке:",
        webhookSetupTitle: "Настройка вебхука",
        webhookSetupIntro: "Автоматически настраивается при инициализации проекта, но при необходимости можно задать вручную:",
        webhookPayloadTitle: "Пример payload вебхука:",
        socketEventsTitle: "Socket события",
        socketEventsIntro: "GitLuma передает live уведомления и активность коммитов через Socket.IO, поэтому дашборд обновляется без перезагрузки.",
        cicdTitle: "CI/CD интеграция",
        cicdIntro: "Подключите GitLuma к пайплайну, чтобы проверять сборки, помечать релизы и сохранять видимость активности после каждого деплоя.",
        availableIntegrationsTitle: "Доступные интеграции",
        integrationCards: [
          { name: "Slack", description: "Получайте уведомления в вашем Slack workspace", features: ["Уведомления о коммитах", "Упоминания команды", "Пользовательские каналы", "Digest режим"], color: "#3A7EE8" },
          { name: "Discord", description: "Отправляйте обновления GitLuma в Discord сервер", features: ["Поддержка вебхуков", "Упоминание участников", "Embed формат", "Маршрутизация по каналам"], color: "#7289DA" },
          { name: "Microsoft Teams", description: "Интеграция с Microsoft Teams для уведомлений", features: ["Adaptive cards", "Посты в канал", "Расширенное форматирование", "Упоминание пользователей"], color: "#0078D4" },
          { name: "Zapier", description: "Автоматизируйте процессы с Zapier", features: ["Trigger действия", "Поддержка нескольких приложений", "Пользовательские workflow", "Запуск по расписанию"], color: "#FF6B2A" },
          { name: "Jira", description: "Синхронизируйте коммиты с задачами Jira", features: ["Автосвязь", "Комментарии к коммитам", "Обновления задач", "Time tracking"], color: "#0052CC" },
          { name: "Linear", description: "Отслеживайте задачи в Linear", features: ["Связка задач", "Обновление статуса", "Cycle tracking", "Синхронизация команды"], color: "#6366F1" },
        ],
        comingSoonTitle: "Скоро",
        comingSoonLabel: "Скоро",
        comingSoonItems: ["GitLab", "Bitbucket", "AWS CodeBuild", "GitKraken", "Figma", "Notion"],
        envTitle: "Переменные окружения",
        envIntro: "Настройте интеграции через переменные окружения:",
      },
      authentication: {
        title: "Аутентификация",
        description: "Защитите аккаунт GitLuma с помощью надежных механизмов аутентификации.",
        sections: [
          { id: "overview", label: "Обзор" },
          { id: "jwt-tokens", label: "JWT токены" },
          { id: "oauth-flow", label: "OAuth поток" },
          { id: "api-keys", label: "API ключи" },
          { id: "refresh-tokens", label: "Refresh токены" },
        ],
        overviewTitle: "Обзор",
        overviewIntro: "GitLuma сочетает GitHub OAuth, короткоживущие JWT access токены и refresh токены, чтобы вход и работа с API были одновременно безопасными и удобными.",
        jwtTitle: "JWT токены",
        jwtIntro: "Access токены авторизуют защищенные запросы, а refresh токены используются для получения нового access токена после истечения срока действия короткого токена.",
        oauthTitle: "OAuth поток",
        oauthIntro: "GitLuma использует GitHub OAuth 2.0 для безопасной аутентификации:",
        oauthSteps: [
          { title: "Пользователь инициирует вход", desc: 'Пользователь нажимает кнопку "Login with GitHub"' },
          { title: "Перенаправление на GitHub", desc: "Пользователь разрешает GitLuma доступ к своему аккаунту" },
          { title: "Получение authorization code", desc: "GitHub возвращает пользователя обратно с authorization code" },
          { title: "Выдача access токена", desc: "Backend GitLuma обменивает code на access токен" },
          { title: "Пользователь аутентифицирован", desc: "Создается сессия пользователя и безопасно сохраняется" },
        ],
        apiKeysTitle: "API ключи",
        apiKeysIntro: "Для доступа к API и использования CLI создавайте персональные access токены в настройках профиля.",
        generatingTitle: "Создание токена:",
        generatingSteps: [
          "1. Перейдите в настройки профиля",
          '2. Нажмите "API Tokens" в боковой панели',
          '3. Нажмите "Generate New Token"',
          "4. Укажите имя токена и срок действия (по желанию)",
          "5. Скопируйте и сохраните его - повторно он не покажется!",
        ],
        usingTitle: "Использование токена:",
        refreshTitle: "Refresh токены",
        refreshIntro: "Клиент может обменять действующий refresh токен на новый access токен без повторного входа пользователя.",
        tokenScopesTitle: "Scopes токена",
        scopes: [
          { code: "read:projects", meaning: "Просмотр списка проектов и деталей проекта" },
          { code: "write:projects", meaning: "Создание, обновление и удаление проектов" },
          { code: "read:commits", meaning: "Просмотр истории коммитов и статистики" },
          { code: "read:members", meaning: "Просмотр участников проекта" },
          { code: "write:members", meaning: "Управление участниками проекта и приглашениями" },
          { code: "admin:webhooks", meaning: "Управление вебхуками и интеграциями" },
        ],
        bestPracticesTitle: "Рекомендации по безопасности",
        bestPractices: [
          { title: "Никогда не делитесь токенами", desc: "Относитесь к токенам как к паролям. Не коммитьте их в version control и не публикуйте." },
          { title: "Регулярно обновляйте", desc: "Периодически создавайте новые токены и отзывайте старые. Устанавливайте срок действия." },
          { title: "Используйте минимальные scopes", desc: "Выдавайте только те права, которые действительно нужны приложению. Избегайте полных admin scopes." },
          { title: "Отслеживайте активность", desc: "Проверяйте журнал безопасности на предмет подозрительных действий и несанкционированного доступа." },
          { title: "Включите 2FA", desc: "Включите двухфакторную аутентификацию в GitHub и GitLuma аккаунтах." },
        ],
        revokeTitle: "Отзыв токенов",
        revokeIntro: "Чтобы отозвать токен:",
        revokeSteps: [
          "1. Перейдите в Profile Settings -> API Tokens",
          "2. Найдите токен, который хотите отозвать",
          '3. Нажмите кнопку "Revoke"',
          "4. Подтвердите действие",
        ],
        revokeWarning: "Предупреждение: отзыв токена немедленно сделает недействительными все API запросы с его использованием.",
      },
      sdk: {
        title: "SDK",
        description: "Интегрируйте GitLuma в свои приложения с помощью официальных SDK и библиотек.",
        sections: [
          { id: "installation", label: "Установка" },
          { id: "quick-start", label: "Быстрый старт" },
          { id: "projects-api", label: "Projects API" },
          { id: "commits-api", label: "Commits API" },
          { id: "typescript-types", label: "Типы TypeScript" },
        ],
        javascriptSdkTitle: "JavaScript SDK",
        installationTitle: "Установка",
        quickStartTitle: "Быстрый старт",
        projectsApiTitle: "Projects API",
        commitsApiTitle: "Commits API",
        membersApiTitle: "Members API",
        reactHooksTitle: "React хуки",
        reactHooksIntro: "Используйте официальные React хуки, чтобы подключать данные GitLuma прямо в компоненты.",
        useProjectsTitle: "Хук useProjects",
        useCommitsTitle: "Хук useCommits",
        providerTitle: "useGitLuma Provider",
        typescriptTitle: "Типы TypeScript",
        typescriptIntro: "Полная поддержка TypeScript со встроенными типами. Отдельные пакеты @types не нужны.",
        errorHandlingTitle: "Обработка ошибок",
        commonErrorCodesTitle: "Частые коды ошибок",
        errorCodes: [
          { code: "NOT_FOUND", meaning: "Ресурс не найден (404)" },
          { code: "UNAUTHORIZED", meaning: "Неверная или отсутствующая аутентификация (401)" },
          { code: "FORBIDDEN", meaning: "Недостаточно прав (403)" },
          { code: "RATE_LIMITED", meaning: "Превышен лимит запросов (429)" },
          { code: "SERVER_ERROR", meaning: "Внутренняя ошибка сервера (500)" },
        ],
        cachingTitle: "Кэширование",
        paginationTitle: "Пагинация",
        examplesTitle: "Примеры",
        dashboardTitle: "Собрать дашборд коммитов",
        reportTitle: "Сформировать отчет по команде",
        supportTitle: "Поддержка и документация",
        supportLinks: [
          { title: "Полная документация API", desc: "Полный reference SDK со всеми методами и типами" },
          { title: "Поддержка сообщества", desc: "Получите помощь от сообщества в Discord" },
        ],
      },
    },
  },
};

function normalizeDocsLang(language) {
  const base = String(language || "en").split("-")[0].toLowerCase();
  return DOCS_CONTENT[base] ? base : "en";
}

export function getDocsContent(language) {
  return DOCS_CONTENT[normalizeDocsLang(language)];
}

export { normalizeDocsLang };
